### ISSUE TITLE
cachy-browser: cannot build

### ISSUE THREAD

**Issue by akku1139** [CachyOS/CachyOS-PKGBUILDS#460] opened 2024-12-16 02:35 UTC
## Digest

```
...
 0:08.62 checking the wasm C compiler can find wasi headers...
 0:08.62 DEBUG: Creating `/tmp/conftest_swa46jg.c` with content:
 0:08.62 DEBUG: | #include <string.h>
 0:08.62 DEBUG: | int
 0:08.62 DEBUG: | main(void)
 0:08.62 DEBUG: | ***
 0:08.62 DEBUG: |
 0:08.62 DEBUG: |   ;
 0:08.62 DEBUG: |   return 0;
 0:08.62 DEBUG: | ***
 0:08.62 DEBUG: Executing: `/usr/sbin/clang -std=gnu99 --target=wasm32-wasi /tmp/conftest_swa46jg.c --sysroot=/usr/share/wasi-sysroot -nodefaultlibs -lc -lwasi-emulated-process-clocks -lc++ -lc++abi %%PORTAGE_WORKDIR%%/wasi-sdk-%%WASI_SDK_VER%%-%%WASI_ARCH%%-linux/lib/clang/%%WASI_SDK_LLVM_VER%%/lib/wasi/libclang_rt.builtins-wasm32.a -c`
 0:08.62 DEBUG: The command returned non-zero exit status 1.
 0:08.62 DEBUG: Its error output was:
 0:08.62 DEBUG: | clang: error: no such file or directory: '%%PORTAGE_WORKDIR%%/wasi-sdk-%%WASI_SDK_VER%%-%%WASI_ARCH%%-linux/lib/clang/%%WASI_SDK_LLVM_VER%%/lib/wasi/libclang_rt.builtins-wasm32.a'
 0:08.62 DEBUG: | clang: warning: -lc: 'linker' input unused [-Wunused-command-line-argument]
 0:08.62 DEBUG: | clang: warning: -lwasi-emulated-process-clocks: 'linker' input unused [-Wunused-command-line-argument]
 0:08.62 DEBUG: | clang: warning: -lc++: 'linker' input unused [-Wunused-command-line-argument]
 0:08.62 DEBUG: | clang: warning: -lc++abi: 'linker' input unused [-Wunused-command-line-argument]
 0:08.62 ERROR: Cannot find wasi headers or problem with the wasm compiler. Please fix the problem. Or build with --without-wasm-sandboxed-libraries.
 0:08.68 W Exception when writing resource usage file: [Errno 2] No such file or directory: '/ext/builder/cachy-browser/src/firefox-133.0/obj/.mozbuild/profile_build_resources.json'
 Config object not found by mach.
*** Fix above errors and then restart with "./mach build"
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'cachy-browser-133.0-1': 
error: packages failed to build: cachy-browser-133.0-1
```

## Full build Log
- 133.0-1
https://github.com/akku1139/auto-aur/actions/runs/12119944990/job/33787573429
- 133.0.3-1
https://github.com/akku1139/auto-aur/actions/runs/12344597568/job/34447361462

## Note
- 132.0.2-1 (AUR) was able to build
https://github.com/akku1139/auto-aur/actions/runs/11996668801/job/33441374838
- 133.0-1 (AUR) also failed to build

**Comment by 1Naim** [comment] 2024-12-16 05:40
> * 133.0-1
>   https://github.com/akku1139/auto-aur/actions/runs/12119944990/job/33787573429
> * 133.0.3-1
>   https://github.com/akku1139/auto-aur/actions/runs/12344597568/job/34447361462

Both logs show it's building for 133.0-1, it's outdated. Duplicate of https://github.com/CachyOS/CachyOS-PKGBUILDS/issues/449

**Closed by 1Naim** 2024-12-16 05:40 UTC
