### ISSUE TITLE
nvidia: Patching of 565.57.01 for Linux kernel 6.12

### ISSUE THREAD

**Issue by Binary-Eater** [CachyOS/CachyOS-PKGBUILDS#417] opened 2024-11-14 02:22 UTC
Hi,

Commit 6c22aadbf6fd ("drm/fbdev-helper: Remove
drm_fb_helper_output_poll_changed()") in the linux kernel removed support for
the .output_poll_changed interface in drm_mode_config_funcs. This callback was
used to handle hotplug events in place of the hotplug interface provided through
fbdev emulation. We verify if this callback is present in the kernel
installation the driver is being built against and omit it if not present.

If this callback is not present, it is safe to assume that filling modes for the
connectors has become the responsibility of the core DRM stack. No replacement
callback needs to be defined for hotplug support to continue working as it
currently does on released kernel trees. The assumption about the core stack
populating the modes capable per connector is based around
drm_fb_helper_hotplug_event which is called thanks to the following.

```
drm_fbdev_ttm_setup
  |_ drm_client_init
    |_ drm_fbdev_ttm_client_funcs
      |_ .hotplug (drm_fbdev_ttm_client_hotplug)
        |_ drm_fbdev_ttm_client_hotplug
```

Because of this, calling drm_client_register and keeping
nv_drm_output_poll_changed is unnecessary for kernel 6.12 since the core stack
handles hotplug events on our behalf through the DRM fbdev API. We noticed users
reporting issues on the NVIDIA forum with regards to this.

https://forums.developer.nvidia.com/t/getting-kernel-null-pointer-dereference-when-unloading-modprobe-r-nvidia-drm/312331

We see users reporting the patched logic hitting the "Failed to
initialize the nv-hotplug-helper DRM client" failure case based on their
dmesg logs. We believe that what then happens is that we failed to init
the drm device (entered a failure path) but the device pointer is on our
list in nv_drm_remove_devices which leads to the kernel panic seen by
the user.

```
BUG: kernel NULL pointer dereference, address: 00000000000000a8
#PF: supervisor read access in kernel mode
#PF: error_code(0x0000) - not-present page
PGD 0 P4D 0 
Oops: Oops: 0000 [#1] PREEMPT SMP NOPTI
CPU: 8 UID: 0 PID: 70806 Comm: modprobe Tainted: P S   U     OE      6.12.0-rc6-1-cachyos-rc-gcc #1 4192acde4edb66f2f1f68c607ab66f58138591f5
Tainted: [P]=PROPRIETARY_MODULE, [S]=CPU_OUT_OF_SPEC, [U]=USER, [O]=OOT_MODULE, [E]=UNSIGNED_MODULE
RIP: 0010:drm_client_dev_unregister+0xd/0xf0
Call Trace:
 <TASK>
 ? __die_body.cold+0x8/0x12
 ? page_fault_oops+0x15a/0x2e0
 ? exc_page_fault+0x81/0x190
 ? asm_exc_page_fault+0x26/0x30
 ? drm_client_dev_unregister+0xd/0xf0
 drm_dev_unregister+0x21/0x1c0
 nv_drm_remove_devices+0x2d/0x60 [nvidia_drm 713ad65fe3ef08e6e23794e19a16790721d8c08f]
 __do_sys_delete_module+0x1d1/0x310
 do_syscall_64+0x82/0x190
 ? __x64_sys_openat+0x1f5/0x230
 ? syscall_exit_to_user_mode+0x10/0x210
 ? do_syscall_64+0x8e/0x190
 ? __x64_sys_openat+0x1f5/0x230
 ? syscall_exit_to_user_mode+0x10/0x210
 ? do_syscall_64+0x8e/0x190
 ? syscall_exit_to_user_mode+0x10/0x210
 ? do_syscall_64+0x8e/0x190
 ? exc_page_fault+0x81/0x190
 entry_SYSCALL_64_after_hwframe+0x76/0x7e
 </TASK>
```

We believe you can safely reduce your patch to what we have shared on
our forum regarding our current 565 driver release and kernel 6.12
compatibility. Our next 565 driver release will patch this as well, but
it unfortunately will likely be release a couple weeks after Linux
kernel 6.12 is tagged.

* https://forums.developer.nvidia.com/t/patch-for-565-57-01-linux-kernel-6-12/313260
* https://github.com/Binary-Eater/open-gpu-kernel-modules/commit/8ac26d3c66ea88b0f80504bdd1e907658b41609d.patch

Thanks,
Rahul Rameshbabu

**Comment by 1Naim** [comment] 2024-11-14 03:06
Acknowledged! Thank you so much for reaching out to us with this. I have created a PR that will use this patch instead of the hacky fix. I have also gotten a few users to test this patch and it seems to work as intended. Once @ptr1337 is available, the PR should get merged and it will be in our repos. I will also sync the patches used in our kernel modules soon.

**Closed** 2024-11-14 09:55 UTC

**Comment by ptr1337** [comment] 2024-11-14 10:06
Thanks for reaching us out! I will send this also to the rpmfusion maintainers and push it into the archlinux repository.
